export const Patches = [
    { "id":  1, "money": 0, "cost": { "money":  2, "time": 1 }, "vertex": [[0,0],[1,0]], "shape": [[true,true]], "initial": true },
    { "id":  2, "money": 0, "cost": { "money":  3, "time": 1 }, "vertex": [[0,0],[1,0],[1,1]], "shape": [[true,true], [true,false]] },
    { "id":  3, "money": 1, "cost": { "money":  2, "time": 3 }, "vertex": [[1,0],[0,1],[1,1],[0,2],[0,3]], "shape": [[false,true],[true,true],[true,false],[true,false]] },
    { "id":  4, "money": 0, "cost": { "money":  1, "time": 2 }, "vertex": [[0,0],[1,0],[1,1],[1,2],[1,3],[2,3]], "shape": [[true,true,false],[false,true,false],[false,true,false],[false,true,true]] },
    { "id":  5, "money": 1, "cost": { "money":  7, "time": 1 }, "vertex": [[0,0],[1,0],[2,0],[3,0],[4,0]], "shape": [[true,true,true,true,true]] },
    { "id":  6, "money": 0, "cost": { "money":  2, "time": 2 }, "vertex": [[0,0],[1,0],[2,0]], "shape": [[true,true,true]] },
    { "id":  7, "money": 1, "cost": { "money":  1, "time": 4 }, "vertex": [], "shape": [[false,true,false],[false,true,false],[true,true,true],[false,true,false],[false,true,false]] },
    { "id":  8, "money": 2, "cost": { "money":  6, "time": 5 }, "vertex": [], "shape": [[true,true],[true,true]] },
    { "id":  9, "money": 1, "cost": { "money":  1, "time": 5 }, "vertex": [], "shape": [[true,true],[false,true],[false,true],[true,true]] },
    { "id": 10, "money": 1, "cost": { "money":  3, "time": 4 }, "vertex": [], "shape": [[true,false],[true,false],[true,true],[true,false]] },
    { "id": 11, "money": 0, "cost": { "money":  4, "time": 2 }, "vertex": [], "shape": [[true,false],[true,true],[true,true],[false,true]] },
    { "id": 12, "money": 0, "cost": { "money":  2, "time": 2 }, "vertex": [], "shape": [[true,true,true],[false,true,false]] },
    { "id": 13, "money": 1, "cost": { "money":  5, "time": 3 }, "vertex": [], "shape": [[false,true,true,false],[true,true,true,true],[false,true,true,false]] },
    { "id": 14, "money": 0, "cost": { "money":  1, "time": 3 }, "vertex": [], "shape": [[true,true], [false,true]] },
    { "id": 15, "money": 3, "cost": { "money": 10, "time": 4 }, "vertex": [], "shape": [[true,false,false],[true,true,false],[false,true,true]] },
    { "id": 16, "money": 2, "cost": { "money":  3, "time": 6 }, "vertex": [], "shape": [[false,true,true],[true,true,false],[false,true,true]] },
    { "id": 17, "money": 2, "cost": { "money":  7, "time": 4 }, "vertex": [], "shape": [[false,true,true,false],[true,true,true,true]] },
    { "id": 18, "money": 1, "cost": { "money":  4, "time": 2 }, "vertex": [], "shape": [[true,true,true],[true,false,false]] },
    { "id": 19, "money": 0, "cost": { "money":  1, "time": 2 }, "vertex": [], "shape": [[true,true],[true,false],[true,true]] },
    { "id": 20, "money": 2, "cost": { "money":  4, "time": 6 }, "vertex": [], "shape": [[true,false,false],[true,true,true]] },
    { "id": 21, "money": 3, "cost": { "money":  8, "time": 6 }, "vertex": [], "shape": [[false,true,true],[false,true,true],[true,true,false]] },
    { "id": 22, "money": 2, "cost": { "money":  5, "time": 5 }, "vertex": [], "shape": [[false,false,true],[true,true,true],[false,false,true]] },
    { "id": 23, "money": 0, "cost": { "money":  2, "time": 2 }, "vertex": [], "shape": [[false,true,true],[true,true,true]] },
    { "id": 24, "money": 2, "cost": { "money": 10, "time": 3 }, "vertex": [], "shape": [[true,true],[true,false],[true,false],[true,false]] },
    { "id": 25, "money": 1, "cost": { "money":  3, "time": 3 }, "vertex": [], "shape": [[true],[true],[true],[true]] },
    { "id": 26, "money": 3, "cost": { "money": 10, "time": 5 }, "vertex": [], "shape": [[true,false],[true,false],[true,true],[true,true]] },
    { "id": 27, "money": 2, "cost": { "money":  5, "time": 4 }, "vertex": [], "shape": [[false,true,false],[true,true,true],[false,true,false]] },
    { "id": 28, "money": 1, "cost": { "money":  3, "time": 2 }, "vertex": [], "shape": [[true,true,false],[false,true,true]] },
    { "id": 30, "money": 0, "cost": { "money":  2, "time": 1 }, "vertex": [], "shape": [[false,true,false],[false,true,true],[true,true,false],[false,true,false]] },
    { "id": 31, "money": 3, "cost": { "money":  7, "time": 6 }, "vertex": [], "shape": [[true,false],[true,true],[false,true]] },
    { "id": 32, "money": 0, "cost": { "money":  0, "time": 3 }, "vertex": [], "shape": [[false,true,false,false],[true,true,true,true],[false,true,false,false]] },
    { "id": 33, "money": 2, "cost": { "money":  7, "time": 2 }, "vertex": [], "shape": [[false,true,false],[false,true,false],[false,true,false],[true,true,true]] }
];
export const TimeBoardBaseLayout = {
    "size": 54,
    "checkpoints": [
        { "type": "money", "position": 5 },
        { "type": "money", "position": 11 },
        { "type": "money", "position": 17 },
        { "type": "patch", "position": 20 },
        { "type": "money", "position": 23 },
        { "type": "patch", "position": 26 },
        { "type": "money", "position": 29 },
        { "type": "patch", "position": 32 },
        { "type": "money", "position": 35 },
        { "type": "money", "position": 41 },
        { "type": "patch", "position": 44 },
        { "type": "money", "position": 47 },
        { "type": "patch", "position": 50 },
        { "type": "money", "position": 53 }
    ]
}