export const Patches = [
    { "id": 1, "shape": ["2x1"], "money": 0, "cost": { "money": 2, "time": 1 }, "initial": true },
    { "id": 2, "shape": ["Lpeque"], "money": 0, "cost": { "money": 3, "time": 1 } },
    { "id": 3, "shape": ["zlarga"], "money": 1, "cost": { "money": 2, "time": 3 } },
    { "id": 4, "shape": [""], "money": 0, "cost": { "money": 1, "time": 2 } },
    { "id": 5, "shape": [""], "money": 1, "cost": { "money": 7, "time": 1 } },
    { "id": 6, "shape": [""], "money": 0, "cost": { "money": 2, "time": 2 } },
    { "id": 7, "shape": [""], "money": 1, "cost": { "money": 1, "time": 4 } },
    { "id": 8, "shape": [""], "money": 2, "cost": { "money": 6, "time": 5 } },
    { "id": 9, "shape": [""], "money": 1, "cost": { "money": 1, "time": 5 } },
    { "id": 10, "shape": [""], "money": 1, "cost": { "money": 3, "time": 4 } },
    { "id": 11, "shape": [""], "money": 0, "cost": { "money": 4, "time": 2 } },
    { "id": 12, "shape": ["tetris"], "money": 0, "cost": { "money": 2, "time": 2 } },
    { "id": 13, "shape": [""], "money": 1, "cost": { "money": 5, "time": 3 } },
    { "id": 14, "shape": [""], "money": 0, "cost": { "money": 1, "time": 3 } },
    { "id": 15, "shape": [""], "money": 3, "cost": { "money": 10, "time": 4 } },
    { "id": 16, "shape": [""], "money": 2, "cost": { "money": 3, "time": 6 } },
    { "id": 17, "shape": [""], "money": 2, "cost": { "money": 7, "time": 4 } },
    { "id": 18, "shape": [""], "money": 1, "cost": { "money": 4, "time": 2 } },
    { "id": 19, "shape": ["U"], "money": 0, "cost": { "money": 1, "time": 2 } },
    { "id": 20, "shape": [""], "money": 2, "cost": { "money": 4, "time": 6 } },
    { "id": 21, "shape": [""], "money": 3, "cost": { "money": 8, "time": 6 } },
    { "id": 22, "shape": [""], "money": 2, "cost": { "money": 5, "time": 5 } },
    { "id": 23, "shape": [""], "money": 0, "cost": { "money": 2, "time": 2 } },
    { "id": 24, "shape": [""], "money": 2, "cost": { "money": 10, "time": 3 } },
    { "id": 25, "shape": [""], "money": 1, "cost": { "money": 3, "time": 3 } },
    { "id": 26, "shape": [""], "money": 3, "cost": { "money": 10, "time": 5 } },
    { "id": 27, "shape": ["x"], "money": 2, "cost": { "money": 5, "time": 4 } },
    { "id": 28, "shape": [""], "money": 1, "cost": { "money": 3, "time": 2 } },
    { "id": 29, "shape": ["h"], "money": 0, "cost": { "money": 2, "time": 3 } },
    { "id": 30, "shape": ["doblet"], "money": 0, "cost": { "money": 2, "time": 1 } },
    { "id": 31, "shape": [""], "money": 3, "cost": { "money": 7, "time": 6 } },
    { "id": 32, "shape": [""], "money": 0, "cost": { "money": 0, "time": 3 } },
    { "id": 33, "shape": [""], "money": 2, "cost": { "money": 7, "time": 2 } }
];
export const TimeBoardBaseLayout = {
    "size": 54,
    "checkpoints": [
        { "type": "money", "position": 5 },
        { "type": "money", "position": 11 },
        { "type": "money", "position": 17 },
        { "type": "patch", "position": 20 },
        { "type": "money", "position": 23 },
        { "type": "patch", "position": 26 },
        { "type": "money", "position": 29 },
        { "type": "patch", "position": 32 },
        { "type": "money", "position": 35 },
        { "type": "money", "position": 41 },
        { "type": "patch", "position": 44 },
        { "type": "money", "position": 47 },
        { "type": "patch", "position": 50 },
        { "type": "money", "position": 53 }
    ]
}